// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/distrieats.proto

// Paquete Protocol Buffers del sistema DistriEats (Laboratorio 3, SD USM 2026-1).
// Define TODOS los mensajes y servicios gRPC que viajan entre las entidades:
// Cliente, Gateway, Broker, Productor y Datanodes.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VectorClock: una entrada por Datanode. clave = node_id ("DN1", "DN2", "DN3").
type VectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       map[string]int64       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_proto_distrieats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{0}
}

func (x *VectorClock) GetEntries() map[string]int64 {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Order: representa un pedido y su estado causal (vector clock adjunto).
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`    // "Ped-S-001", "Ped-C1-001", ...
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // cliente que lo originó (vacío si viene del productor)
	Restaurant    string                 `protobuf:"bytes,3,opt,name=restaurant,proto3" json:"restaurant,omitempty"`             // BurgerNode, DockerPizza, SushiStream, GopherTacos
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                     // Recibido, Preparando, En Camino, Entregado, Cancelado
	Clock         *VectorClock           `protobuf:"bytes,5,opt,name=clock,proto3" json:"clock,omitempty"`                       // reloj vectorial del emisor
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // instante de la última modificación (UnixNano)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_distrieats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Order) GetRestaurant() string {
	if x != nil {
		return x.Restaurant
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetClock() *VectorClock {
	if x != nil {
		return x.Clock
	}
	return nil
}

func (x *Order) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CrearPedidoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // idempotencia (generador propio)
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Restaurant    string                 `protobuf:"bytes,4,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	Items         []string               `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearPedidoRequest) Reset() {
	*x = CrearPedidoRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearPedidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearPedidoRequest) ProtoMessage() {}

func (x *CrearPedidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearPedidoRequest.ProtoReflect.Descriptor instead.
func (*CrearPedidoRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{2}
}

func (x *CrearPedidoRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CrearPedidoRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CrearPedidoRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CrearPedidoRequest) GetRestaurant() string {
	if x != nil {
		return x.Restaurant
	}
	return ""
}

func (x *CrearPedidoRequest) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type CrearPedidoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Order         *Order                 `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	DatanodeId    string                 `protobuf:"bytes,4,opt,name=datanode_id,json=datanodeId,proto3" json:"datanode_id,omitempty"` // Datanode que procesó (para el mensaje RYW)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearPedidoResponse) Reset() {
	*x = CrearPedidoResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearPedidoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearPedidoResponse) ProtoMessage() {}

func (x *CrearPedidoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearPedidoResponse.ProtoReflect.Descriptor instead.
func (*CrearPedidoResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{3}
}

func (x *CrearPedidoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CrearPedidoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CrearPedidoResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CrearPedidoResponse) GetDatanodeId() string {
	if x != nil {
		return x.DatanodeId
	}
	return ""
}

type ConsultarEstadoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarEstadoRequest) Reset() {
	*x = ConsultarEstadoRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarEstadoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarEstadoRequest) ProtoMessage() {}

func (x *ConsultarEstadoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarEstadoRequest.ProtoReflect.Descriptor instead.
func (*ConsultarEstadoRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{4}
}

func (x *ConsultarEstadoRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ConsultarEstadoRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ConsultarEstadoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	DatanodeId    string                 `protobuf:"bytes,3,opt,name=datanode_id,json=datanodeId,proto3" json:"datanode_id,omitempty"`        // Datanode consultado (afinidad o round robin)
	FromAffinity  bool                   `protobuf:"varint,4,opt,name=from_affinity,json=fromAffinity,proto3" json:"from_affinity,omitempty"` // true si se resolvió por afinidad de sesión
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarEstadoResponse) Reset() {
	*x = ConsultarEstadoResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarEstadoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarEstadoResponse) ProtoMessage() {}

func (x *ConsultarEstadoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarEstadoResponse.ProtoReflect.Descriptor instead.
func (*ConsultarEstadoResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{5}
}

func (x *ConsultarEstadoResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ConsultarEstadoResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *ConsultarEstadoResponse) GetDatanodeId() string {
	if x != nil {
		return x.DatanodeId
	}
	return ""
}

func (x *ConsultarEstadoResponse) GetFromAffinity() bool {
	if x != nil {
		return x.FromAffinity
	}
	return false
}

type UpdateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`                          // incluye vector clock del emisor
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // idempotencia extremo a extremo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateOrderRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *UpdateOrderRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type UpdateOrderResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Applied        bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`                                    // true si el estado entrante se aplicó
	ResultingOrder *Order                 `protobuf:"bytes,2,opt,name=resulting_order,json=resultingOrder,proto3" json:"resulting_order,omitempty"` // estado final tras merge/resolución
	DatanodeId     string                 `protobuf:"bytes,3,opt,name=datanode_id,json=datanodeId,proto3" json:"datanode_id,omitempty"`             // Datanode que respondió
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                                     // detalle (p. ej. error de negocio)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateOrderResponse) Reset() {
	*x = UpdateOrderResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderResponse) ProtoMessage() {}

func (x *UpdateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOrderResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *UpdateOrderResponse) GetResultingOrder() *Order {
	if x != nil {
		return x.ResultingOrder
	}
	return nil
}

func (x *UpdateOrderResponse) GetDatanodeId() string {
	if x != nil {
		return x.DatanodeId
	}
	return ""
}

func (x *UpdateOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	DatanodeId    string                 `protobuf:"bytes,3,opt,name=datanode_id,json=datanodeId,proto3" json:"datanode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *GetOrderResponse) GetDatanodeId() string {
	if x != nil {
		return x.DatanodeId
	}
	return ""
}

type GossipSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"` // snapshot local del emisor
	SenderClock   *VectorClock           `protobuf:"bytes,2,opt,name=sender_clock,json=senderClock,proto3" json:"sender_clock,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipSyncRequest) Reset() {
	*x = GossipSyncRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipSyncRequest) ProtoMessage() {}

func (x *GossipSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipSyncRequest.ProtoReflect.Descriptor instead.
func (*GossipSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{10}
}

func (x *GossipSyncRequest) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *GossipSyncRequest) GetSenderClock() *VectorClock {
	if x != nil {
		return x.SenderClock
	}
	return nil
}

func (x *GossipSyncRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

type GossipSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"` // estado del receptor para fusionar de vuelta
	ReceiverId    string                 `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipSyncResponse) Reset() {
	*x = GossipSyncResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipSyncResponse) ProtoMessage() {}

func (x *GossipSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipSyncResponse.ProtoReflect.Descriptor instead.
func (*GossipSyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{11}
}

func (x *GossipSyncResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *GossipSyncResponse) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{12}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{13}
}

func (x *PingResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{14}
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"` // estado completo del Datanode (para Reporte.txt)
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{15}
}

func (x *SnapshotResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *SnapshotResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RYWEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DatanodeId    string                 `protobuf:"bytes,3,opt,name=datanode_id,json=datanodeId,proto3" json:"datanode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RYWEntry) Reset() {
	*x = RYWEntry{}
	mi := &file_proto_distrieats_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RYWEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RYWEntry) ProtoMessage() {}

func (x *RYWEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RYWEntry.ProtoReflect.Descriptor instead.
func (*RYWEntry) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{16}
}

func (x *RYWEntry) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RYWEntry) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RYWEntry) GetDatanodeId() string {
	if x != nil {
		return x.DatanodeId
	}
	return ""
}

type AuditoriaRYWRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditoriaRYWRequest) Reset() {
	*x = AuditoriaRYWRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditoriaRYWRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditoriaRYWRequest) ProtoMessage() {}

func (x *AuditoriaRYWRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditoriaRYWRequest.ProtoReflect.Descriptor instead.
func (*AuditoriaRYWRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{17}
}

type AuditoriaRYWResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*RYWEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditoriaRYWResponse) Reset() {
	*x = AuditoriaRYWResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditoriaRYWResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditoriaRYWResponse) ProtoMessage() {}

func (x *AuditoriaRYWResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditoriaRYWResponse.ProtoReflect.Descriptor instead.
func (*AuditoriaRYWResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{18}
}

func (x *AuditoriaRYWResponse) GetEntries() []*RYWEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FinEventosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalEventos  int32                  `protobuf:"varint,1,opt,name=total_eventos,json=totalEventos,proto3" json:"total_eventos,omitempty"` // cuántas líneas emitió el productor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinEventosRequest) Reset() {
	*x = FinEventosRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinEventosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinEventosRequest) ProtoMessage() {}

func (x *FinEventosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinEventosRequest.ProtoReflect.Descriptor instead.
func (*FinEventosRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{19}
}

func (x *FinEventosRequest) GetTotalEventos() int32 {
	if x != nil {
		return x.TotalEventos
	}
	return 0
}

type FinEventosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinEventosResponse) Reset() {
	*x = FinEventosResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinEventosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinEventosResponse) ProtoMessage() {}

func (x *FinEventosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinEventosResponse.ProtoReflect.Descriptor instead.
func (*FinEventosResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{20}
}

func (x *FinEventosResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_distrieats_proto protoreflect.FileDescriptor

const file_proto_distrieats_proto_rawDesc = "" +
	"\n" +
	"\x16proto/distrieats.proto\x12\n" +
	"distrieats\"\x89\x01\n" +
	"\vVectorClock\x12>\n" +
	"\aentries\x18\x01 \x03(\v2$.distrieats.VectorClock.EntriesEntryR\aentries\x1a:\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xc4\x01\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1e\n" +
	"\n" +
	"restaurant\x18\x03 \x01(\tR\n" +
	"restaurant\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12-\n" +
	"\x05clock\x18\x05 \x01(\v2\x17.distrieats.VectorClockR\x05clock\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\xa1\x01\n" +
	"\x12CrearPedidoRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x1e\n" +
	"\n" +
	"restaurant\x18\x04 \x01(\tR\n" +
	"restaurant\x12\x14\n" +
	"\x05items\x18\x05 \x03(\tR\x05items\"\x93\x01\n" +
	"\x13CrearPedidoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x05order\x18\x03 \x01(\v2\x11.distrieats.OrderR\x05order\x12\x1f\n" +
	"\vdatanode_id\x18\x04 \x01(\tR\n" +
	"datanodeId\"P\n" +
	"\x16ConsultarEstadoRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"\x9e\x01\n" +
	"\x17ConsultarEstadoResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12'\n" +
	"\x05order\x18\x02 \x01(\v2\x11.distrieats.OrderR\x05order\x12\x1f\n" +
	"\vdatanode_id\x18\x03 \x01(\tR\n" +
	"datanodeId\x12#\n" +
	"\rfrom_affinity\x18\x04 \x01(\bR\ffromAffinity\"\\\n" +
	"\x12UpdateOrderRequest\x12'\n" +
	"\x05order\x18\x01 \x01(\v2\x11.distrieats.OrderR\x05order\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"\xa6\x01\n" +
	"\x13UpdateOrderResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12:\n" +
	"\x0fresulting_order\x18\x02 \x01(\v2\x11.distrieats.OrderR\x0eresultingOrder\x12\x1f\n" +
	"\vdatanode_id\x18\x03 \x01(\tR\n" +
	"datanodeId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"r\n" +
	"\x10GetOrderResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12'\n" +
	"\x05order\x18\x02 \x01(\v2\x11.distrieats.OrderR\x05order\x12\x1f\n" +
	"\vdatanode_id\x18\x03 \x01(\tR\n" +
	"datanodeId\"\x97\x01\n" +
	"\x11GossipSyncRequest\x12)\n" +
	"\x06orders\x18\x01 \x03(\v2\x11.distrieats.OrderR\x06orders\x12:\n" +
	"\fsender_clock\x18\x02 \x01(\v2\x17.distrieats.VectorClockR\vsenderClock\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\"`\n" +
	"\x12GossipSyncResponse\x12)\n" +
	"\x06orders\x18\x01 \x03(\v2\x11.distrieats.OrderR\x06orders\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\tR\n" +
	"receiverId\"\r\n" +
	"\vPingRequest\"=\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"\x11\n" +
	"\x0fSnapshotRequest\"V\n" +
	"\x10SnapshotResponse\x12)\n" +
	"\x06orders\x18\x01 \x03(\v2\x11.distrieats.OrderR\x06orders\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"c\n" +
	"\bRYWEntry\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1f\n" +
	"\vdatanode_id\x18\x03 \x01(\tR\n" +
	"datanodeId\"\x15\n" +
	"\x13AuditoriaRYWRequest\"F\n" +
	"\x14AuditoriaRYWResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.distrieats.RYWEntryR\aentries\"8\n" +
	"\x11FinEventosRequest\x12#\n" +
	"\rtotal_eventos\x18\x01 \x01(\x05R\ftotalEventos\"$\n" +
	"\x12FinEventosResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\x96\x02\n" +
	"\x0eGatewayService\x12N\n" +
	"\vCrearPedido\x12\x1e.distrieats.CrearPedidoRequest\x1a\x1f.distrieats.CrearPedidoResponse\x12Z\n" +
	"\x0fConsultarEstado\x12\".distrieats.ConsultarEstadoRequest\x1a#.distrieats.ConsultarEstadoResponse\x12X\n" +
	"\x13ObtenerAuditoriaRYW\x12\x1f.distrieats.AuditoriaRYWRequest\x1a .distrieats.AuditoriaRYWResponse2\xdf\x02\n" +
	"\rBrokerService\x12S\n" +
	"\x10EnrutarEscritura\x12\x1e.distrieats.UpdateOrderRequest\x1a\x1f.distrieats.UpdateOrderResponse\x12K\n" +
	"\x0eEnrutarLectura\x12\x1b.distrieats.GetOrderRequest\x1a\x1c.distrieats.GetOrderResponse\x12X\n" +
	"\x15EmitirEventoLogistico\x12\x1e.distrieats.UpdateOrderRequest\x1a\x1f.distrieats.UpdateOrderResponse\x12R\n" +
	"\x11SenalarFinEventos\x12\x1d.distrieats.FinEventosRequest\x1a\x1e.distrieats.FinEventosResponse2\xf7\x02\n" +
	"\x0fDatanodeService\x12N\n" +
	"\vUpdateOrder\x12\x1e.distrieats.UpdateOrderRequest\x1a\x1f.distrieats.UpdateOrderResponse\x12E\n" +
	"\bGetOrder\x12\x1b.distrieats.GetOrderRequest\x1a\x1c.distrieats.GetOrderResponse\x12K\n" +
	"\n" +
	"GossipSync\x12\x1d.distrieats.GossipSyncRequest\x1a\x1e.distrieats.GossipSyncResponse\x129\n" +
	"\x04Ping\x12\x17.distrieats.PingRequest\x1a\x18.distrieats.PingResponse\x12E\n" +
	"\bSnapshot\x12\x1b.distrieats.SnapshotRequest\x1a\x1c.distrieats.SnapshotResponseB\x18Z\x16distrieats/proto/pb;pbb\x06proto3"

var (
	file_proto_distrieats_proto_rawDescOnce sync.Once
	file_proto_distrieats_proto_rawDescData []byte
)

func file_proto_distrieats_proto_rawDescGZIP() []byte {
	file_proto_distrieats_proto_rawDescOnce.Do(func() {
		file_proto_distrieats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_distrieats_proto_rawDesc), len(file_proto_distrieats_proto_rawDesc)))
	})
	return file_proto_distrieats_proto_rawDescData
}

var file_proto_distrieats_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_distrieats_proto_goTypes = []any{
	(*VectorClock)(nil),             // 0: distrieats.VectorClock
	(*Order)(nil),                   // 1: distrieats.Order
	(*CrearPedidoRequest)(nil),      // 2: distrieats.CrearPedidoRequest
	(*CrearPedidoResponse)(nil),     // 3: distrieats.CrearPedidoResponse
	(*ConsultarEstadoRequest)(nil),  // 4: distrieats.ConsultarEstadoRequest
	(*ConsultarEstadoResponse)(nil), // 5: distrieats.ConsultarEstadoResponse
	(*UpdateOrderRequest)(nil),      // 6: distrieats.UpdateOrderRequest
	(*UpdateOrderResponse)(nil),     // 7: distrieats.UpdateOrderResponse
	(*GetOrderRequest)(nil),         // 8: distrieats.GetOrderRequest
	(*GetOrderResponse)(nil),        // 9: distrieats.GetOrderResponse
	(*GossipSyncRequest)(nil),       // 10: distrieats.GossipSyncRequest
	(*GossipSyncResponse)(nil),      // 11: distrieats.GossipSyncResponse
	(*PingRequest)(nil),             // 12: distrieats.PingRequest
	(*PingResponse)(nil),            // 13: distrieats.PingResponse
	(*SnapshotRequest)(nil),         // 14: distrieats.SnapshotRequest
	(*SnapshotResponse)(nil),        // 15: distrieats.SnapshotResponse
	(*RYWEntry)(nil),                // 16: distrieats.RYWEntry
	(*AuditoriaRYWRequest)(nil),     // 17: distrieats.AuditoriaRYWRequest
	(*AuditoriaRYWResponse)(nil),    // 18: distrieats.AuditoriaRYWResponse
	(*FinEventosRequest)(nil),       // 19: distrieats.FinEventosRequest
	(*FinEventosResponse)(nil),      // 20: distrieats.FinEventosResponse
	nil,                             // 21: distrieats.VectorClock.EntriesEntry
}
var file_proto_distrieats_proto_depIdxs = []int32{
	21, // 0: distrieats.VectorClock.entries:type_name -> distrieats.VectorClock.EntriesEntry
	0,  // 1: distrieats.Order.clock:type_name -> distrieats.VectorClock
	1,  // 2: distrieats.CrearPedidoResponse.order:type_name -> distrieats.Order
	1,  // 3: distrieats.ConsultarEstadoResponse.order:type_name -> distrieats.Order
	1,  // 4: distrieats.UpdateOrderRequest.order:type_name -> distrieats.Order
	1,  // 5: distrieats.UpdateOrderResponse.resulting_order:type_name -> distrieats.Order
	1,  // 6: distrieats.GetOrderResponse.order:type_name -> distrieats.Order
	1,  // 7: distrieats.GossipSyncRequest.orders:type_name -> distrieats.Order
	0,  // 8: distrieats.GossipSyncRequest.sender_clock:type_name -> distrieats.VectorClock
	1,  // 9: distrieats.GossipSyncResponse.orders:type_name -> distrieats.Order
	1,  // 10: distrieats.SnapshotResponse.orders:type_name -> distrieats.Order
	16, // 11: distrieats.AuditoriaRYWResponse.entries:type_name -> distrieats.RYWEntry
	2,  // 12: distrieats.GatewayService.CrearPedido:input_type -> distrieats.CrearPedidoRequest
	4,  // 13: distrieats.GatewayService.ConsultarEstado:input_type -> distrieats.ConsultarEstadoRequest
	17, // 14: distrieats.GatewayService.ObtenerAuditoriaRYW:input_type -> distrieats.AuditoriaRYWRequest
	6,  // 15: distrieats.BrokerService.EnrutarEscritura:input_type -> distrieats.UpdateOrderRequest
	8,  // 16: distrieats.BrokerService.EnrutarLectura:input_type -> distrieats.GetOrderRequest
	6,  // 17: distrieats.BrokerService.EmitirEventoLogistico:input_type -> distrieats.UpdateOrderRequest
	19, // 18: distrieats.BrokerService.SenalarFinEventos:input_type -> distrieats.FinEventosRequest
	6,  // 19: distrieats.DatanodeService.UpdateOrder:input_type -> distrieats.UpdateOrderRequest
	8,  // 20: distrieats.DatanodeService.GetOrder:input_type -> distrieats.GetOrderRequest
	10, // 21: distrieats.DatanodeService.GossipSync:input_type -> distrieats.GossipSyncRequest
	12, // 22: distrieats.DatanodeService.Ping:input_type -> distrieats.PingRequest
	14, // 23: distrieats.DatanodeService.Snapshot:input_type -> distrieats.SnapshotRequest
	3,  // 24: distrieats.GatewayService.CrearPedido:output_type -> distrieats.CrearPedidoResponse
	5,  // 25: distrieats.GatewayService.ConsultarEstado:output_type -> distrieats.ConsultarEstadoResponse
	18, // 26: distrieats.GatewayService.ObtenerAuditoriaRYW:output_type -> distrieats.AuditoriaRYWResponse
	7,  // 27: distrieats.BrokerService.EnrutarEscritura:output_type -> distrieats.UpdateOrderResponse
	9,  // 28: distrieats.BrokerService.EnrutarLectura:output_type -> distrieats.GetOrderResponse
	7,  // 29: distrieats.BrokerService.EmitirEventoLogistico:output_type -> distrieats.UpdateOrderResponse
	20, // 30: distrieats.BrokerService.SenalarFinEventos:output_type -> distrieats.FinEventosResponse
	7,  // 31: distrieats.DatanodeService.UpdateOrder:output_type -> distrieats.UpdateOrderResponse
	9,  // 32: distrieats.DatanodeService.GetOrder:output_type -> distrieats.GetOrderResponse
	11, // 33: distrieats.DatanodeService.GossipSync:output_type -> distrieats.GossipSyncResponse
	13, // 34: distrieats.DatanodeService.Ping:output_type -> distrieats.PingResponse
	15, // 35: distrieats.DatanodeService.Snapshot:output_type -> distrieats.SnapshotResponse
	24, // [24:36] is the sub-list for method output_type
	12, // [12:24] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_distrieats_proto_init() }
func file_proto_distrieats_proto_init() {
	if File_proto_distrieats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_distrieats_proto_rawDesc), len(file_proto_distrieats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_distrieats_proto_goTypes,
		DependencyIndexes: file_proto_distrieats_proto_depIdxs,
		MessageInfos:      file_proto_distrieats_proto_msgTypes,
	}.Build()
	File_proto_distrieats_proto = out.File
	file_proto_distrieats_proto_goTypes = nil
	file_proto_distrieats_proto_depIdxs = nil
}
